const EXACT_EXTENSION_STATUS_ATTR_NAME = 'data-exact-extension-status';
const EXACT_EXTENSION_STATUS_ATTR_VALUE__DISABLED = 'disabled';

export {
    EXACT_EXTENSION_STATUS_ATTR_NAME,
    EXACT_EXTENSION_STATUS_ATTR_VALUE__DISABLED,
};
